# Tahap Build
FROM node:18-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# Ganti IP ini dengan IP Publik EC2 Backend Anda saat presentasi
ENV VITE_API_BASE_URL=http://15.135.188.209:8081
RUN npm run build

# Tahap Produksi (Nginx)
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
# Konfigurasi Nginx untuk React Router
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
